# Generated by Django 4.1.5 on 2023-04-10 02:22

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phoneNumber', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:            '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$'), users.models.validate_phone_number])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('service_provider', models.CharField(choices=[('AT&T', 'AT&T'), ('T-Mobile', 'T-Mobile'), ('Verizon', 'Verizon'), ('Metro', 'Metro'), ('Cricket', 'Cricket'), ('Simple Mobile', 'Simple Mobile'), ('H20', 'H20'), ('Lyca Mobile', 'Lyca Mobile'), ('Ultra Mobile', 'Ultra Mobile'), ('Net 10', 'Net 10'), ('Straight Talk', 'Straight Talk'), ('Tracfone', 'Tracfone'), ('Boost Mobile', 'Boost Mobile'), ('Virgin Mobile', 'Virgin Mobile'), ('Sprint', 'Sprint'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('accept_devices_trade_in', models.BooleanField(default=True)),
                ('accept_devices_buy', models.BooleanField(default=True)),
                ('accept_devices_sell', models.BooleanField(default=True)),
                ('accept_device_repair', models.BooleanField(default=True)),
                ('accept_purchase', models.BooleanField(default=True)),
                ('blacklisted', models.BooleanField(default=False)),
                ('blacklisted_reason', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/profile_pics')),
                ('notes', models.TextField(blank=True, default='', max_length=500)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
