# Generated by Django 4.1.5 on 2023-04-10 05:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Device Brand',
                'verbose_name_plural': 'Device Brands',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('taxable', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='yes', max_length=3)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('N/A', 'n/a'), ('At&t', 'at&t'), ('T-mobile', 't-mobile'), ('Verizon', 'verizon'), ('Metro', 'metro'), ('Cricket', 'cricket'), ('Simple Mobile', 'simple mobile'), ('H20', 'h20'), ('Lyca Mobile', 'lyca mobile'), ('Ultra Mobile', 'ultra mobile'), ('Net 10', 'net 10'), ('Straight Talk', 'straight talk'), ('Tracfone', 'tracfone'), ('Boost Mobile', 'boost mobile'), ('Virgin Mobile', 'virgin mobile'), ('Sprint', 'sprint'), ('Unlocked', 'unlocked'), ('Other', 'other'), ('Unknown', 'unknown'), ('آخر', 'آخر')], default='unknown', max_length=25)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('compatibility', models.CharField(choices=[('GSM', 'gsm'), ('CDMA', 'cdma'), ('GSM/CDMA', 'gsm/cdma'), ('Other', 'other'), ('Unknown', 'unknown'), ('آخر', 'آخر'), ('N/A', 'n/a')], default='unknown', max_length=25)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField(default=datetime.datetime.now)),
                ('device_created_date', models.DateTimeField(auto_now_add=True)),
                ('device_updated_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='static/reports/device_reports/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/images/device_photos/')),
                ('status', models.CharField(choices=[('New', 'new'), ('Used', 'used'), ('Refurbished', 'refurbished'), ('Repaired', 'repaired'), ('Available', 'available'), ('Unavailable', 'unavailable'), ('Reserved', 'reserved'), ('Recycled', 'recycled'), ('Unknown', 'unknown'), ('آخر', 'آخر')], default='unknown', max_length=25)),
                ('grade', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('Unknown', 'unknown')], default='unknown', max_length=25)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DeviceColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Device Color',
                'verbose_name_plural': 'Device Colors',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DeviceDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(max_length=50, unique=True)),
                ('defect_description', models.TextField(blank=True, max_length=500, null=True)),
                ('defect_solution', models.TextField(default='Unknown', max_length=500)),
            ],
            options={
                'verbose_name': 'Device Defect',
                'verbose_name_plural': 'Device Defects',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_series', models.CharField(default='N/A', max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Device Model',
                'verbose_name_plural': 'Device Models',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_name', models.CharField(max_length=200)),
                ('labor_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('labor_description', models.TextField(blank=True, null=True)),
                ('labor_risk', models.CharField(choices=[('Minimal', 'minimal'), ('very low', 'very low'), ('Low', 'low'), ('Medium', 'medium'), ('High', 'high'), ('Very High', 'very high'), ('Too High', 'too high')], default='low', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(default='Unknown', max_length=200)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=999.99, max_digits=12)),
                ('onhand_quantity', models.IntegerField(default=0)),
                ('min_stock_threshold', models.IntegerField(default=0)),
                ('max_stock_threshold', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('added_to_cart_count', models.IntegerField(default=0)),
                ('sale_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('sale_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='static/images/store/products')),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('ms_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(default='Unknown', max_length=200)),
                ('phone', models.CharField(default='Unknown', max_length=200)),
                ('email', models.CharField(default='Unknown', max_length=200)),
                ('address', models.CharField(default='Unknown', max_length=200)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_status', models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in progress'), ('Completed', 'completed'), ('Back Ordered', 'back ordered'), ('Beyond Repair', 'beyond repair'), ('Cannot be Repaired', 'cannot be repaired'), ('Cancelled', 'cancelled'), ('Rejected', 'rejected'), ('Unknown', 'unknown'), ('آخر', 'آخر')], default='pending', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_created_date', models.DateTimeField(auto_now_add=True)),
                ('order_updated_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ('id',),
            },
        ),
    ]
