# Generated by Django 4.1.5 on 2023-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=111, max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
