# Generated by Django 4.1.5 on 2023-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14, unique=True, verbose_name='Phone Number'),
        ),
    ]
