# Generated by Django 4.1.5 on 2023-04-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='device',
        ),
    ]
